# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: samuelpersonal
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: gamers-pub-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: gamerspub-sls-api

package:
  individually: true
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminDeleteUser
            - cognito-idp:AdminUpdateUserAttributes
            - cognito-idp:AdminGetUser
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - s3:PutObject
            - s3:GetObject
            - s3:PutObjectAcl
            - s3:GetObjectAcl
          Resource:
            - !GetAtt GamersPubUserPool.Arn
            - !GetAtt GamersPubTable.Arn
            - !GetAtt GamersPubBucket.Arn
            - !Join ['', [!GetAtt GamersPubBucket.Arn, '/*']]
            - !GetAtt GamersPubBucket.Arn
  environment:
    COGNITO_CLIENT_ID: !Ref GamersPubUserPoolClient
    COGNITO_POOL_ID: !Ref GamersPubUserPool
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt GamersPubUserPool.ProviderURL
        audience:
          - !Ref GamersPubUserPoolClient
    cors:
      allowedOrigins:
        - "http://localhost:3000"
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - HEAD
        - OPTIONS
      maxAge: 300

custom:
  Esbuild:
  bundle: true
  minify: true
  sourcemap: false
  target: node20
  exclude:
    - "node_modules/**"
    - "@aws-sdk/*"
  platform: node
  concurrency: 10

resources:
  Resources:
    GamersPubUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: GamersPubUserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
            TemporaryPasswordValidityDays: 2
        Schema:
          - Name: nickname
            Mutable: true
            Required: false
            AttributeDataType: String
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: family_name
            Mutable: true
            Required: true
            AttributeDataType: String
    GamersPubUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: GamersPubUserPoolClient
        UserPoolId: !Ref GamersPubUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        AccessTokenValidity: 1
        RefreshTokenValidity: 15
        TokenValidityUnits:
          AccessToken: days
          RefreshToken: days
    GamersPubTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GamersPubTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S #S == String / N == Number / B == Binary
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi1_pk
            AttributeType: S
          - AttributeName: gsi1_sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
            - AttributeName: gsi1_pk
              KeyType: HASH
            - AttributeName: gsi1_sk
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
    GamersPubBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: gamers-pub-bucket
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
              - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "http://localhost:3000"
              ExposedHeaders:
                - Etag
                - x-amz-meta-custom-header
                - Content-Length
              MaxAge: 3000



functions:
  hello:
    handler: src/functions/helloWorld.handler
    events:
      - httpApi:
          path: /
          method: GET
  signUp:
    handler: src/functions/auth/signUp.handler
    events:
      - httpApi:
          path: /auth/sign-up
          method: POST
  signIn:
    handler: src/functions/auth/signIn.handler
    events:
      - httpApi:
          path: /auth/sign-in
          method: POST
  accountConfirmation:
  # TODO: Resolve InvalidLambdaException error
    handler: src/functions/auth/accountConfirmation.handler
    events:
      - httpApi:
          path: /auth/verify-account
          method: POST
  refreshToken:
    handler: src/functions/auth/refreshToken.handler
    events:
      - httpApi:
          path: /auth/refresh-token
          method: POST
  forgotPassword:
    handler: src/functions/auth/forgotPassword.handler
    events:
      - httpApi:
          path: /auth/forgot-password
          method: POST
  # TODO: Resolve InvalidLambdaException error
  resetPassword:
    handler: src/functions/auth/resetPassword.handler
    events:
      - httpApi:
          path: /auth/reset-password
          method: POST
  cognitoCustomMessage:
    handler: src/functions/auth/cognitoCustomMessage.handler
    events:
      - cognitoUserPool:
          pool: GamersPubUserPool
          trigger: CustomMessage
          existing: true
          # forceDeploy: true
  storeUser:
    handler: src/functions/auth/storeUser.handler
    events:
      - cognitoUserPool:
          pool: GamersPubUserPool
          trigger: PostConfirmation
          existing: true
  getUserInformation:
    handler: src/functions/users/getUserInformation.handler
    events:
      - httpApi:
          path: /users
          method: GET
          authorizer:
            name: CognitoAuthorizer
  updateUser:
    handler: src/functions/users/updateUser.handler
    events:
      - httpApi:
          path: /users
          method: PUT
          authorizer:
            name: CognitoAuthorizer
  createReview:
    handler: src/functions/reviews/createReview.handler
    events:
      - httpApi:
          path: /reviews
          method: POST
          authorizer:
            name: CognitoAuthorizer
  getReviewsByUser:
  # TODO: Ensure that pagination is working properly
    handler: src/functions/reviews/getReviewsByUser.handler
    events:
      - httpApi:
          path: /reviews
          method: GET
          authorizer:
            name: CognitoAuthorizer
  getReviewById:
    handler: src/functions/reviews/getReviewById.handler
    events:
      - httpApi:
          path: /reviews/{reviewId}
          method: GET
          authorizer:
            name: CognitoAuthorizer
  getRandomReviews:
    handler: src/functions/reviews/getRandomReviews.handler
    events:
      - httpApi:
          path: /reviews/random
          method: GET
  updateReview:
    handler: src/functions/reviews/updateReview.handler
    events:
    - httpApi:
        path: /reviews/{reviewId}
        method: PUT
        authorizer:
          name: CognitoAuthorizer
  deleteReview:
    handler: src/functions/reviews/deleteReview.handler
    events:
    - httpApi:
        path: /reviews/{reviewId}
        method: DELETE
        authorizer:
          name: CognitoAuthorizer
  getUserChatbotHistory:
    handler: src/functions/chatbot/getUserChatbotHistory.handler
    events:
      - httpApi:
          path: /chatbot
          method: GET
          authorizer:
            name: CognitoAuthorizer
  getChatbotHistoryById:
    handler: src/functions/chatbot/getChatbotHistoryById.handler
    events:
      - httpApi:
          path: /chatbot/{chatHistoryId}
          method: GET
          authorizer:
            name: CognitoAuthorizer
  sendChatbotMessage:
    handler: src/functions/chatbot/sendChatbotMessage.handler
    events:
     - httpApi:
         path: /chatbot/{chatHistoryId}
         method: POST
         authorizer:
           name: CognitoAuthorizer
    timeout: 12
  deleteChatbotHistory:
    handler: src/functions/chatbot/deleteChatbotHistory.handler
    events:
      - httpApi:
          path: /chatbot/{chatHistoryId}
          method: DELETE
          authorizer:
            name: CognitoAuthorizer
  getPresignedUrl:
    handler: src/functions/upload/getPresignedUrl.handler
    events:
      - httpApi:
          path: /uploads/upload-file
          method: POST
          authorizer:
            name: CognitoAuthorizer
  getFileWithPresignedUrl:
    handler: src/functions/upload/getFileWithPresignedUrl.handler
    events:
      - httpApi:
          path: /uploads/get-file
          method: POST
          authorizer:
            name: CognitoAuthorizer
  fileUploadTrigger:
    handler: src/functions/upload/fileUploadTrigger.handler
    events:
      - s3:
          bucket: gamers-pub-bucket
          event: s3:ObjectCreated:Put
          rules:
            - prefix: uploads/
          existing: true
